apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-lab04
  labels:
    app: front-lab04
spec:
  selector:
    matchLabels:
      app: front-lab04
  replicas: 1
  template:
    metadata:
      labels:
        app: front-lab04
    spec:
      containers:
        - name: front-lab04
          image: euijeonggo/front-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
